#!/bin/bash
set -e
DIR=$1
CUTOFF=$2
ID=$3

echo "CUTOFF = $CUTOFF"
echo "ID = $ID"

init () {
  mkdir -p $DIR/clusters
  mkdir -p $DIR/joined
  mkdir -p $DIR/reprs
}

label_join () {
  # Label and join reads
    for file in $p/*.fasta
    do
      echo "Labelling and joining $file"
      rm -f $DIR/joined/joined.fasta
      python src/join_pairs.py $file $p >> DIR/joined/joined.fasta
    done
  done
}

cluster () {
  # Cluster joined reads with CDHIT
  echo "clustering"
  sh src/run_cdhit.sh $ID both.fasta clusters_$ID.fasta > clusters_$ID.txt
}

filter () {
  # Filter out rep. reads that belong to clusters only consting of themself
  echo "Filtering [cutoff = $CUTOFF]"
  python src/filter.py clusters_$ID.fasta.clstr clusters_$ID.fasta $CUTOFF
}

init

label_join

cluster

filter
